#!/usr/bin/env bash
# Co-LRIO Host Configuration
# Generated by setup_ssh.sh on Mon Sep 29 04:49:42 PM CEST 2025

# === YOUR HOSTS ===
# HOST_ROBOT_0="exo.sim.informatik.tu-darmstadt.de"
# HOST_MAPPING=\"exo.sim.informatik.tu-darmstadt.de\"
# HOST_VISUALIZATION=\"\"  # Keep local for display

# === ACTIVE CONFIGURATION ===
# Uncomment and modify the lines above, then uncomment these:
HOST_ROBOT_0=""
HOST_MAPPING=\"\"
HOST_VISUALIZATION=\"\"
